### ISSUE TITLE
Native Type Coverage - Default Config so nötig ?

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/rexstan#237]
Durch diese KOnfiguration werden beim Aufrüf über die Console die
entsprechenden Meldung gesendet. Das führt dazu, dass in meinen 
Pipelin eprozessen, diese immer, auch ausgegeben werden und ich
diese nicht unterdrücken oder entfernen kann. 

Ich sehe darin im Moment keinen Vorteil. Kann man diese einfach
entfernen?

[native-type-cover](https://github.com/FriendsOfREDAXO/rexstan/blob/main/config/native-type-coverage.neon)

```
services:
    -
        class: Symplify\PHPStanRules\Rules\Explicit\PropertyTypeDeclarationSeaLevelRule
        tags: [phpstan.rules.rule]
        arguments:
            minimalLevel: 0.99
            printSuggestions: false

    -
        class: Symplify\PHPStanRules\Rules\Explicit\ParamTypeDeclarationSeaLevelRule
        tags: [phpstan.rules.rule]
        arguments:
            minimalLevel: 0.99
            printSuggestions: false

    -
        class: Symplify\PHPStanRules\Rules\Explicit\ReturnTypeDeclarationSeaLevelRule
        tags: [phpstan.rules.rule]
        arguments:
            minimalLevel: 0.99
            printSuggestions: false
```
